version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: gestione-unisp-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gestione_unisp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: xcvbn
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: gestione-unisp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xcvbn
      POSTGRES_DB: gestione_unisp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gestione-unisp-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
